spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true

#logging:
#  level:
#    #로그를 통해서 찍어줌
#    org.hibernate.SQL: debug
